server:
  port: ${PORT:8080}
---
spring:
  datasource:
    db-name: salary
    host: localhost
    port: 5432
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always # remove it after LiquiBase/ Flyway implemented
      encoding: UTF-8
---
jwt:
  secret: asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4